### ISSUE TITLE
Eats up memory

### ISSUE THREAD

**Issue by hurzl** [plepe/mapnik-render-image#1]
After 10 seconds it is at 5GB memory. Input: berlin-latest.osm

**Comment by plepe** [comment]
mapnik-render-image is just a frontend for mapnik. I'd guess there is another problem.

Can you please explain your setup in more detail? What kind of style are you trying to render (link to Mapnik .xml)? Which parameters are you using?

**Comment by hurzl** [comment]
I guess berlin is just too big for py-mapnik. I now use osmfilter and don't need rendering any more ;)

**Comment by plepe** [comment]
Yes, this will be the reason. If you'd like to render large extracts, you should import the data into a database (preferably PostgreSQL + PostGIS).
